services:
  db:
    image: mariadb:10.11
    container_name: toybattles-db
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: microvolts-db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./microvolts-db.sql:/docker-entrypoint-initdb.d/microvolts-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  auth-server:
    build: .
    command: ["./AuthServer.elf"]
    container_name: toybattles-auth
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "13000:13000"
    volumes:
      - ./Setup/config.ini:/app/Setup/config.ini:ro

  main-server:
    build: .
    command: ["./MainServer.elf"]
    container_name: toybattles-main
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "13005:13005"
      - "14005:14005"
    volumes:
      - ./Setup/config.ini:/app/Setup/config.ini:ro
      - ./data/:/app/data/:ro

  cast-server:
    build: .
    command: ["./CastServer.elf"]
    container_name: toybattles-cast
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "13006:13006"
      - "14006:14006"
    volumes:
      - ./Setup/config.ini:/app/Setup/config.ini:ro
      - ./data/:/app/data/:ro
