services:
  db:
    image: mariadb:10.11
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: microvolts-db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./microvolts-db.sql:/docker-entrypoint-initdb.d/microvolts-db.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u admin -p$DB_PASSWORD"]
      start_period: 2s
      interval: 10s
      timeout: 5s
      retries: 3

  auth-server:
    build: .
    command: "auth"
    stop_grace_period: 2s
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "13000:13000"
    volumes:
      - ./Setup/config.docker.ini:/app/Setup/config.ini:ro

  main-server:
    build: .
    command: "main"
    stop_grace_period: 2s
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "13005:13005"
      - "14005:14005"
    volumes:
      - ./Setup/config.docker.ini:/app/Setup/config.ini:ro
      - ./data/:/app/data/:ro

  cast-server:
    build: .
    command: "cast"
    stop_grace_period: 2s
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "13006:13006"
      - "14006:14006"
    volumes:
      - ./Setup/config.docker.ini:/app/Setup/config.ini:ro
      - ./data/:/app/data/:ro
